"""Collector routes: list registered collectors + platform capability catalog.

Catalog covers representative Actors from the 2026-08-12 Apify exploration
(56 original + 22 new: PR media monitoring + remaining ecommerce/B2B actors),
plus TikHub social endpoints and internal collectors (GitHub, RSS).
Organised into 10 groups:
  tikhub_social   – TikHub REST API (TikTok/Instagram/XHS/YouTube/Reddit/X/Threads/LinkedIn/Lemon8)
  apify_social    – P0 social platforms (Instagram, Facebook, TikTok, YouTube, X, Reddit)
  apify_ecommerce – P0/P1 ecommerce & reviews (Amazon, Walmart, eBay, Etsy, Shopify …)
  apify_google    – Google ecosystem (Search, Maps, Trends, News, AI Overviews …)
  apify_ai_search – AI-native search (ChatGPT, Perplexity, Gemini)
  apify_ads       – Ad intelligence (Meta Ads, Google Ads, TikTok Ads, Snap Ads)
  apify_b2b       – B2B/jobs/content (LinkedIn, Hacker News, Bluesky, Telegram, Indeed …)
  apify_media     – PR media monitoring (Forbes/Consumer Reports/Parents/Babylist …)
  apify_open_web  – Generic web crawling (Website Content Crawler, Web Scraper, RAG)
  github          – GitHub REST API
  rss_web         – RSS / public web snapshots
"""

from __future__ import annotations

from fastapi import APIRouter

from data_intelligence_hub.api.deps import SessionDep
from data_intelligence_hub.repositories.collectors import list_collectors
from data_intelligence_hub.schemas.collector import CollectorResponse
from data_intelligence_hub.schemas.collector_catalog import (
    CollectorCatalogEntry,
    CollectorCatalogResponse,
    CollectorEndpointMetadata,
)
from data_intelligence_hub.services.collector_catalog import ensure_collectors_seeded

router = APIRouter(tags=["collectors"])


@router.get("", response_model=list[CollectorResponse])
async def list_collector_items(session: SessionDep) -> list[CollectorResponse]:
    await ensure_collectors_seeded(session)
    collectors = await list_collectors(session)
    return [CollectorResponse.model_validate(collector) for collector in collectors]


@router.get("/catalog", response_model=CollectorCatalogResponse)
async def get_collector_catalog() -> CollectorCatalogResponse:
    """Capability catalog: all registered collectors and their endpoints.

    Used by the Console /platforms page to render ability cards.
    """
    tikhub_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_video_search",
            label="TikTok 视频搜索",
            platform="tiktok",
            description="按关键词搜索 TikTok 公开视频，返回视频文案、互动数据和作者信息",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "cursor", "sort_type"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_user_posts",
            label="TikTok 账号视频",
            platform="tiktok",
            description="获取指定 TikTok 账号的公开视频列表",
            status="verified",
            required_params=["unique_id"],
            optional_params=["max_items", "max_cursor"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_hashtag_posts",
            label="TikTok 话题视频",
            platform="tiktok",
            description="获取指定话题下的 TikTok 视频列表",
            status="verified",
            required_params=["ch_id"],
            optional_params=["max_items", "cursor"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_instagram_search",
            label="Instagram 关键词搜索",
            platform="instagram",
            description="按关键词搜索 Instagram 公开帖子，返回帖子内容和互动数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_instagram_user_posts",
            label="Instagram 账号帖子",
            platform="instagram",
            description="获取指定 Instagram 账号的公开帖子列表",
            status="verified",
            required_params=["user_id"],
            optional_params=["max_items", "max_id"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_xiaohongshu_search",
            label="小红书笔记搜索",
            platform="xiaohongshu",
            description="按关键词搜索小红书公开笔记，返回笔记标题、内容和互动数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "sort_type"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_youtube_search",
            label="YouTube 视频搜索",
            platform="youtube",
            description="按关键词搜索 YouTube 公开视频",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_youtube_channel_videos",
            label="YouTube 频道视频",
            platform="youtube",
            description="获取指定 YouTube 频道的公开视频列表",
            status="verified",
            required_params=["channel_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_reddit_search",
            label="Reddit 关键词搜索",
            platform="reddit",
            description="按关键词搜索 Reddit 公开帖子",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_reddit_subreddit_posts",
            label="Reddit 社区帖子",
            platform="reddit",
            description="获取指定 Subreddit 的公开帖子列表",
            status="verified",
            required_params=["subreddit"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_x_search",
            label="X / Twitter 关键词搜索",
            platform="x",
            description="按关键词搜索 X 公开推文",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_x_user_tweets",
            label="X / Twitter 账号推文",
            platform="x",
            description="获取指定 X 账号的公开推文列表",
            status="verified",
            required_params=["username"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_threads_search",
            label="Threads 关键词搜索",
            platform="threads",
            description="按关键词搜索 Threads 公开帖子，返回帖子内容和互动数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_threads_user_posts",
            label="Threads 账号帖子",
            platform="threads",
            description="获取指定 Threads 账号的公开帖子列表",
            status="verified",
            required_params=["username"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_threads_post_comments",
            label="Threads 帖子评论",
            platform="threads",
            description="获取指定 Threads 帖子的评论列表",
            status="verified",
            required_params=["post_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_linkedin_user_posts",
            label="LinkedIn 用户帖子",
            platform="linkedin",
            description="获取指定 LinkedIn 用户的公开帖子列表",
            status="verified",
            required_params=["username"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_linkedin_company_profile",
            label="LinkedIn 企业主页",
            platform="linkedin",
            description="获取指定 LinkedIn 企业的主页信息和动态",
            status="verified",
            required_params=["company_username"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_linkedin_company_posts",
            label="LinkedIn 企业帖子",
            platform="linkedin",
            description="获取指定 LinkedIn 企业账号的公开帖子列表",
            status="verified",
            required_params=["company_username"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_linkedin_search_jobs",
            label="LinkedIn 职位搜索",
            platform="linkedin",
            description="按关键词和地区搜索 LinkedIn 职位，用于竞品招聘和组织信号分析",
            status="verified",
            required_params=["keyword"],
            optional_params=["location", "max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="job",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_linkedin_job_detail",
            label="LinkedIn 职位详情",
            platform="linkedin",
            description="获取指定 LinkedIn 职位的详细信息：职责、要求、薪资和公司背景",
            status="verified",
            required_params=["job_id"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="job",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_linkedin_post_comments",
            label="LinkedIn 帖子评论",
            platform="linkedin",
            description="获取指定 LinkedIn 帖子的评论列表，用于行业讨论和 VOC 分析",
            status="verified",
            required_params=["post_urn"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_lemon8_search",
            label="Lemon8 关键词搜索",
            platform="lemon8",
            description="按关键词搜索 Lemon8 公开帖子（字节系母婴/时尚内容平台）",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_lemon8_user_posts",
            label="Lemon8 账号帖子",
            platform="lemon8",
            description="获取指定 Lemon8 账号的公开帖子列表",
            status="verified",
            required_params=["user_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_lemon8_trending",
            label="Lemon8 趋势内容",
            platform="lemon8",
            description="获取 Lemon8 平台当前趋势话题和热门帖子",
            status="verified",
            required_params=[],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="trend",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_ads_search",
            label="TikTok 广告创意搜索",
            platform="tiktok",
            description="按关键词搜索 TikTok 广告库中的在投广告素材",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "country_code", "period"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="ad",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_top_ads",
            label="TikTok 热门广告榜单",
            platform="tiktok",
            description="获取 TikTok 广告库热门广告榜单，含曝光量和互动率",
            status="verified",
            required_params=[],
            optional_params=["country_code", "period", "max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="ad",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_shop_products",
            label="TikTok Shop 商品搜索",
            platform="tiktok",
            description="搜索 TikTok Shop 在售商品，返回商品详情、价格和销量数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "sort_type"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="product",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_creator_info",
            label="TikTok 达人信息",
            platform="tiktok",
            description="获取 TikTok 达人账号的商业合作资质、粉丝画像和内容表现",
            status="verified",
            required_params=["unique_id"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_instagram_post_comments",
            label="Instagram 帖子评论",
            platform="instagram",
            description="获取指定 Instagram 帖子的评论列表，用于 VOC 分析",
            status="verified",
            required_params=["shortcode"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_youtube_video_comments",
            label="YouTube 视频评论",
            platform="youtube",
            description="获取指定 YouTube 视频的评论列表，用于产品反馈和 VOC 分析",
            status="verified",
            required_params=["video_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_reddit_post_comments",
            label="Reddit 帖子评论",
            platform="reddit",
            description="获取指定 Reddit 帖子的评论列表，用于社区讨论和 VOC 分析",
            status="verified",
            required_params=["post_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_live_search",
            label="TikTok 直播搜索",
            platform="tiktok",
            description="按关键词搜索 TikTok 公开直播间，返回直播间信息和主播数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_live_room_detail",
            label="TikTok 直播间详情",
            platform="tiktok",
            description="获取指定 TikTok 直播间的在线人数、商品列表和互动数据",
            status="verified",
            required_params=["room_id"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_live_user",
            label="TikTok 主播直播间",
            platform="tiktok",
            description="获取指定 TikTok 账号的直播间状态和历史直播数据",
            status="verified",
            required_params=["unique_id"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_youtube_trending",
            label="YouTube 趋势视频",
            platform="youtube",
            description="获取 YouTube 当前热门趋势视频列表，支持按地区和分类筛选",
            status="verified",
            required_params=[],
            optional_params=["country_code", "category_id"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="trend",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_reddit_trending",
            label="Reddit 热门帖子",
            platform="reddit",
            description="获取 Reddit 全站或指定频道的热门帖子 Feed",
            status="verified",
            required_params=[],
            optional_params=["subreddit", "max_items", "timeframe"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="trend",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_x_trending",
            label="X / Twitter 趋势话题",
            platform="x",
            description="获取 X 平台当前热门趋势话题列表",
            status="verified",
            required_params=[],
            optional_params=["country_code"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="trend",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_user_followers",
            label="TikTok 粉丝列表",
            platform="tiktok",
            description="获取指定 TikTok 账号的粉丝列表，用于达人受众分析",
            status="verified",
            required_params=["unique_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_instagram_user_followers",
            label="Instagram 粉丝列表",
            platform="instagram",
            description="获取指定 Instagram 账号的粉丝列表，用于达人网络和受众分析",
            status="verified",
            required_params=["user_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_x_user_followers",
            label="X / Twitter 粉丝列表",
            platform="x",
            description="获取指定 X 账号的粉丝列表，用于达人受众和传播网络分析",
            status="verified",
            required_params=["username"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_creator_insights",
            label="TikTok 创作者搜索洞察",
            platform="tiktok",
            description="获取 TikTok 创作者搜索洞察数据：受众搜索行为、关键词流量和内容机会",
            status="verified",
            required_params=["unique_id"],
            optional_params=["time_range"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_creator_insights_trend",
            label="TikTok 创作者洞察趋势",
            platform="tiktok",
            description="获取 TikTok 创作者的历史表现趋势：互动率、曝光量和增长趋势",
            status="verified",
            required_params=["unique_id"],
            optional_params=["time_range"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_creator_account_health",
            label="TikTok 创作者账号健康",
            platform="tiktok",
            description="获取 TikTok 创作者账号健康状态：违规记录、限流风险和合规评分",
            status="verified",
            required_params=["unique_id"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="account",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_ads_detail",
            label="TikTok 广告详情",
            platform="tiktok",
            description="获取指定 TikTok 广告的详细信息：创意内容、投放数据和落地页",
            status="verified",
            required_params=["ad_id"],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="ad",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_tiktok_ads_keyword_suggest",
            label="TikTok 广告关键词建议",
            platform="tiktok",
            description="获取 TikTok 广告投放关键词建议和搜索量数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["country_code"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="ad",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_douyin_video_search",
            label="抖音视频搜索",
            platform="douyin",
            description="按关键词搜索抖音公开视频，返回视频文案、互动数据和作者信息",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "cursor", "sort_type"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_douyin_user_posts",
            label="抖音账号视频",
            platform="douyin",
            description="获取指定抖音账号的公开视频列表",
            status="verified",
            required_params=["sec_user_id"],
            optional_params=["max_items", "max_cursor"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_douyin_hot_search",
            label="抖音热搜榜",
            platform="douyin",
            description="获取抖音实时热搜榜单，含热度值和话题标签",
            status="verified",
            required_params=[],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="trend",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_douyin_comments",
            label="抖音视频评论",
            platform="douyin",
            description="获取指定抖音视频的评论列表，用于 VOC 分析",
            status="verified",
            required_params=["aweme_id"],
            optional_params=["max_items", "cursor"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_douyin_brand_hot_search",
            label="抖音品牌热搜榜",
            platform="douyin",
            description="获取抖音品牌热搜榜详情，用于品牌声量监测",
            status="verified",
            required_params=[],
            optional_params=[],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="trend",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_bilibili_video_search",
            label="B站视频搜索",
            platform="bilibili",
            description="按关键词搜索 B 站公开视频，返回视频信息和互动数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "page"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_bilibili_user_videos",
            label="B站账号视频",
            platform="bilibili",
            description="获取指定 B 站 UP 主的公开投稿视频列表",
            status="verified",
            required_params=["mid"],
            optional_params=["max_items", "page"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_bilibili_comments",
            label="B站视频评论",
            platform="bilibili",
            description="获取指定 B 站视频的评论列表，用于产品反馈和 VOC 分析",
            status="verified",
            required_params=["oid"],
            optional_params=["max_items", "page"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="comment",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_weibo_search",
            label="微博关键词搜索",
            platform="weibo",
            description="按关键词搜索微博公开内容，返回帖子文案和互动数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "page"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_weibo_user_posts",
            label="微博账号帖子",
            platform="weibo",
            description="获取指定微博账号的公开帖子列表",
            status="verified",
            required_params=["uid"],
            optional_params=["max_items", "page"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_kuaishou_search",
            label="快手视频搜索",
            platform="kuaishou",
            description="按关键词搜索快手公开视频，返回视频信息和互动数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_kuaishou_user_posts",
            label="快手账号视频",
            platform="kuaishou",
            description="获取指定快手账号的公开视频列表",
            status="verified",
            required_params=["userId"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_wechat_search",
            label="微信公众号搜索",
            platform="wechat",
            description="按关键词搜索微信公众号文章，返回文章标题和摘要",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items", "page"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_wechat_channels_video",
            label="微信视频号视频",
            platform="wechat",
            description="获取指定微信视频号账号的公开视频列表",
            status="verified",
            required_params=["username"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_zhihu_search",
            label="知乎内容搜索",
            platform="zhihu",
            description="按关键词搜索知乎公开内容，含问题、回答和文章",
            status="verified",
            required_params=["keyword"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
        CollectorEndpointMetadata(
            endpoint_type="tikhub_zhihu_question_answers",
            label="知乎问题回答",
            platform="zhihu",
            description="获取指定知乎问题的回答列表，用于行业洞察和 VOC 分析",
            status="verified",
            required_params=["question_id"],
            optional_params=["max_items"],
            cost_hint="~$0.001/条",
            provider="TikHub REST API",
            content_type="post",
            method="tikhub",
        ),
    ]

    # === P0 Social Platforms (Instagram, Facebook, TikTok, YouTube, X, Reddit) ===
    apify_social = [
        CollectorEndpointMetadata(
            endpoint_type="apify_instagram_scraper",
            label="Instagram Scraper",
            platform="instagram",
            description="Instagram 帖子搜索：关键词、话题、账号；支持 Reels / Stories",
            status="verified",
            required_params=["search"],
            optional_params=["resultsLimit", "resultsType"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/instagram-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_instagram_profile_scraper",
            label="Instagram Profile Scraper",
            platform="instagram",
            description="Instagram 账号资料和帖子列表",
            status="verified",
            required_params=["usernames"],
            optional_params=["resultsLimit"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/instagram-profile-scraper)",
            content_type="account",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_facebook_posts_scraper",
            label="Facebook Posts Scraper",
            platform="facebook",
            description="Facebook 公开帖子：页面、群组、用户时间线",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxPosts", "maxPostDate"],
            cost_hint="$0.0017+",
            provider="Apify Actor (apify/facebook-posts-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_facebook_comments_scraper",
            label="Facebook Comments Scraper",
            platform="facebook",
            description="Facebook 帖子评论：产品反馈、危机信号",
            status="verified",
            required_params=["startUrls"],
            optional_params=["resultsLimit", "includeNestedComments"],
            cost_hint="$0.0017+",
            provider="Apify Actor (apify/facebook-comments-scraper)",
            content_type="comment",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_scraper",
            label="TikTok Scraper",
            platform="tiktok",
            description="TikTok 视频搜索：关键词、话题、账号；UGC 趋势监测",
            status="verified",
            required_params=["searchQueries"],
            optional_params=["resultsPerPage", "hashtags", "profiles"],
            cost_hint="$0.5+",
            provider="Apify Actor (clockworks/tiktok-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_comments_scraper",
            label="TikTok Comments Scraper",
            platform="tiktok",
            description="TikTok 视频评论：产品痛点、购买意向",
            status="verified",
            required_params=["postURLs"],
            optional_params=["commentsPerPost", "maxRepliesPerComment"],
            cost_hint="按事件计费",
            provider="Apify Actor (clockworks/tiktok-comments-scraper)",
            content_type="comment",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_youtube_scraper",
            label="YouTube Scraper",
            platform="youtube",
            description="YouTube 视频搜索：测评、教程、竞品视频",
            status="verified",
            required_params=["searchQueries"],
            optional_params=["maxResults", "startUrls", "downloadSubtitles"],
            cost_hint="按事件计费",
            provider="Apify Actor (streamers/youtube-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_youtube_comments_scraper",
            label="YouTube Comments Scraper",
            platform="youtube",
            description="YouTube 评论：产品体验、问题挖掘",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxComments", "sortCommentsBy"],
            cost_hint="$0.5+",
            provider="Apify Actor (streamers/youtube-comments-scraper)",
            content_type="comment",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_x_tweet_scraper",
            label="X / Twitter Scraper",
            platform="x",
            description="X 推文搜索：实时舆情、媒体传播、危机预警",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems", "startUrls", "twitterHandles"],
            cost_hint="按事件计费",
            provider="Apify Actor (apidojo/tweet-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_reddit_scraper",
            label="Reddit Scraper",
            platform="reddit",
            description="Reddit 帖子与评论：真实育儿讨论、竞品口碑",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems", "searches", "skipComments"],
            cost_hint="$0.04+",
            provider="Apify Actor (trudax/reddit-scraper-lite)",
            content_type="post",
            method="apify",
        ),
    ]

    # === P0/P1 E-commerce & Reviews (Amazon, Walmart, Temu, SHEIN, Trustpilot, App Reviews) ===
    apify_ecommerce = [
        CollectorEndpointMetadata(
            endpoint_type="apify_amazon_product_scraper",
            label="Amazon Product Scraper",
            platform="amazon",
            description="Amazon 商品详情：价格、库存、变体、Q&A",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems", "country"],
            cost_hint="按事件计费",
            provider="Apify Actor (junglee/Amazon-crawler)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_amazon_reviews_scraper",
            label="Amazon Reviews Scraper",
            platform="amazon",
            description="Amazon 商品评价：竞品口碑、痛点挖掘",
            status="verified",
            required_params=["asin"],
            optional_params=["maxReviews", "country"],
            cost_hint="按事件计费",
            provider="Apify Actor (junglee/amazon-reviews-scraper)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_walmart_product_scraper",
            label="Walmart Product Scraper",
            platform="walmart",
            description="Walmart 商品详情：价格监测、库存追踪",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="免费",
            provider="Apify Actor (e-commerce/walmart-product-detail-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_walmart_reviews_scraper",
            label="Walmart Reviews Scraper",
            platform="walmart",
            description="Walmart 商品评价：北美市场反馈",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="按事件计费",
            provider="Apify Actor (e-commerce/walmart-reviews-scraper)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_temu_products_scraper",
            label="Temu Products Scraper",
            platform="temu",
            description="Temu 商品详情：低价竞品监测",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (amit123/temu-products-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_shein_product_scraper",
            label="SHEIN Product Scraper",
            platform="shein",
            description="SHEIN 商品详情：快时尚竞品监测",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (shahidirfan/shein-product-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_aliexpress_products_scraper",
            label="AliExpress Products Scraper",
            platform="aliexpress",
            description="AliExpress 商品详情：供应链监测",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (devcake/aliexpress-products-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_shop_scraper",
            label="TikTok Shop Scraper",
            platform="tiktok_shop",
            description="TikTok Shop 商品：直播电商监测",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (clockworks/tiktok-shop-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_trustpilot_reviews_scraper",
            label="Trustpilot Reviews Scraper",
            platform="trustpilot",
            description="Trustpilot 评价：品牌口碑、竞品对比",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="$0.5+",
            provider="Apify Actor (memo23/trustpilot-scraper-ppe)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_appstore_reviews_scraper",
            label="Apple App Store Reviews",
            platform="appstore",
            description="App Store 评价：移动应用反馈",
            status="verified",
            required_params=["appId"],
            optional_params=["maxReviews", "country"],
            cost_hint="按事件计费",
            provider="Apify Actor (johnvc/apple-app-store-reviews-api)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_play_reviews_scraper",
            label="Google Play Reviews Scraper",
            platform="google_play",
            description="Google Play 应用评价：按 App ID + 语言分页，适合 App VOC 和版本反馈分析",
            status="verified",
            required_params=["appId"],
            optional_params=["maxReviews", "language", "country", "sort"],
            cost_hint="按事件计费",
            provider="Apify Actor (neatrat/google-play-store-reviews-scraper)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_ebay_product_scraper",
            label="eBay Product Scraper",
            platform="ebay",
            description="eBay 商品详情：二手市场价格、竞品库存",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (dtrungtin/ebay-items-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_ebay_sold_listings_scraper",
            label="eBay Sold Listings Scraper",
            platform="ebay",
            description="eBay 成交价搜索：二级市场真实成交价格与竞品价格带分析",
            status="verified",
            required_params=["search"],
            optional_params=["maxItems", "condition", "sortOrder"],
            cost_hint="按事件计费",
            provider="Apify Actor (caffein.dev/ebay-sold-listings)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_etsy_scraper",
            label="Etsy Scraper",
            platform="etsy",
            description="Etsy 商品与评价：手工/母婴品类趋势",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (automation-lab/etsy-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tripadvisor_reviews_scraper",
            label="Tripadvisor Reviews Scraper",
            platform="tripadvisor",
            description="Tripadvisor 评价：旅行相关品类口碑",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="按事件计费",
            provider="Apify Actor (maxcopell/tripadvisor-reviews)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_yelp_scraper",
            label="Yelp Scraper",
            platform="yelp",
            description="Yelp 商家评价：本地口碑、服务反馈",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="按事件计费",
            provider="Apify Actor (tri_angle/yelp-scraper)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_booking_scraper",
            label="Booking.com Scraper",
            platform="booking",
            description="Booking.com 酒店评价：差旅相关消费反馈",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="按事件计费",
            provider="Apify Actor (dtrungtin/booking-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_airbnb_scraper",
            label="Airbnb Scraper",
            platform="airbnb",
            description="Airbnb 房源与评价：旅行消费场景监测",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxListings"],
            cost_hint="按事件计费",
            provider="Apify Actor (dtrungtin/airbnb-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_shopify_scraper",
            label="Shopify Store Scraper",
            platform="shopify",
            description="Shopify 独立站商品和评价：DTC 竞品监测",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (clearpath/shopify-store-leads)",
            content_type="product",
            method="apify",
        ),
    ]

    # === Google Ecosystem (Search, Maps, Trends, News, AI Overviews) ===
    apify_google = [
        CollectorEndpointMetadata(
            endpoint_type="apify_google_search_scraper",
            label="Google Search Scraper",
            platform="google",
            description="Google 搜索结果：SEO 排名、竞品曝光",
            status="verified",
            required_params=["queries"],
            optional_params=["maxPagesPerQuery", "resultsPerPage"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/google-search-scraper)",
            content_type="search",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_maps_scraper",
            label="Google Maps Scraper",
            platform="google_maps",
            description="Google Maps 地点：门店信息、联系方式",
            status="verified",
            required_params=["searchStringsArray"],
            optional_params=["maxCrawledPlacesPerSearch"],
            cost_hint="按事件计费",
            provider="Apify Actor (compass/crawler-google-places)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_maps_reviews_scraper",
            label="Google Maps Reviews Scraper",
            platform="google_maps",
            description="Google Maps 评价：门店口碑、服务反馈",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="按事件计费",
            provider="Apify Actor (compass/Google-Maps-Reviews-Scraper)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_trends_scraper",
            label="Google Trends Scraper",
            platform="google_trends",
            description="Google Trends 趋势：搜索热度、季节性",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["timeRange", "geo"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/google-trends-scraper)",
            content_type="trend",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_news_scraper",
            label="Google News Scraper",
            platform="google_news",
            description="Google News 新闻：媒体报道、品牌曝光",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (data_xplorer/google-news-scraper-fast)",
            content_type="news",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_ai_overviews_scraper",
            label="Google AI Overviews Scraper",
            platform="google",
            description="Google AI Overviews：AI 生成摘要、来源引用",
            status="verified",
            required_params=["queries"],
            optional_params=["maxQueries"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/google-ai-overviews-scraper)",
            content_type="ai_answer",
            method="apify",
        ),
    ]

    # === AI-native Search (ChatGPT, Perplexity, Gemini) ===
    apify_ai_search = [
        CollectorEndpointMetadata(
            endpoint_type="apify_chatgpt_search_scraper",
            label="ChatGPT Search Scraper",
            platform="chatgpt",
            description="ChatGPT 搜索结果：AI 原生检索",
            status="verified",
            required_params=["queries"],
            optional_params=["maxQueries"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/chatgpt-search-scraper)",
            content_type="ai_answer",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_perplexity_search_scraper",
            label="Perplexity Search Scraper",
            platform="perplexity",
            description="Perplexity 搜索结果：AI 问答引用",
            status="verified",
            required_params=["queries"],
            optional_params=["maxQueries"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/perplexity-search-scraper)",
            content_type="ai_answer",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_gemini_search_scraper",
            label="Gemini Search Scraper",
            platform="gemini",
            description="Gemini 搜索结果：Google AI 检索",
            status="verified",
            required_params=["queries"],
            optional_params=["maxQueries"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/gemini-search-scraper)",
            content_type="ai_answer",
            method="apify",
        ),
    ]

    # === Ad Intelligence (Meta Ads, Google Ads, TikTok Ads, Snap Ads, Pinterest Ads) ===
    apify_ads = [
        CollectorEndpointMetadata(
            endpoint_type="apify_facebook_ads_scraper",
            label="Meta Ads Library Scraper",
            platform="facebook_ads",
            description="Meta 广告透明库：竞品广告创意、投放策略",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems", "countries"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/facebook-ads-scraper)",
            content_type="ad",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_google_ads_scraper",
            label="Google Ads Scraper",
            platform="google_ads",
            description="Google 广告透明中心：竞品搜索广告",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (lexis-solutions/google-ads-scraper)",
            content_type="ad",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_ads_scraper",
            label="TikTok Ads Scraper",
            platform="tiktok_ads",
            description="TikTok 广告库：短视频广告创意",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (lexis-solutions/tiktok-ads-scraper)",
            content_type="ad",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_snapchat_ads_scraper",
            label="Snap Ads Scraper",
            platform="snapchat_ads",
            description="Snapchat 广告库：年轻用户广告",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (lexis-solutions/snapchat-ads-scraper)",
            content_type="ad",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_pinterest_ads_scraper",
            label="Pinterest Ads Scraper",
            platform="pinterest_ads",
            description="Pinterest 广告：视觉营销创意",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (shahidirfan/Pinterest-Ads-Scraper)",
            content_type="ad",
            method="apify",
        ),
    ]

    # === B2B / Content / Jobs
    # (LinkedIn, Threads, Pinterest, Glassdoor, Product Hunt, Crunchbase) ===
    apify_b2b = [
        CollectorEndpointMetadata(
            endpoint_type="apify_linkedin_company_posts_scraper",
            label="LinkedIn Company Posts Scraper",
            platform="linkedin",
            description="LinkedIn 公司动态：B2B 内容营销",
            status="verified",
            required_params=["companyUrls"],
            optional_params=["maxPosts"],
            cost_hint="按事件计费",
            provider="Apify Actor (harvestapi/linkedin-company-posts)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_linkedin_jobs_scraper",
            label="LinkedIn Jobs Scraper",
            platform="linkedin",
            description="LinkedIn 职位搜索：竞品招聘信号、区域扩张和职能投入分析",
            status="verified",
            required_params=["keyword"],
            optional_params=["location", "maxItems", "datePosted"],
            cost_hint="免费",
            provider="Apify Actor (freshdata/linkedin-job-scraper)",
            content_type="job",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_linkedin_company_employees_scraper",
            label="LinkedIn Company Employees Scraper",
            platform="linkedin",
            description="LinkedIn 企业员工列表：无需 Cookie，用于组织规模和人才结构分析",
            status="verified",
            required_params=["companyUrl"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (apimaestro/linkedin-company-employees-scraper-no-cookies)",
            content_type="account",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_linkedin_company_search_scraper",
            label="LinkedIn Company Search Scraper",
            platform="linkedin",
            description="按关键词和行业搜索 LinkedIn 公司列表，用于竞品发现和市场扩张研究",
            status="verified",
            required_params=["keyword"],
            optional_params=["location", "industry", "maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (khadinakbar/linkedin-company-search-scraper)",
            content_type="account",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_threads_profile_scraper",
            label="Threads Profile Scraper",
            platform="threads",
            description="Threads 账号资料：新兴社交监测",
            status="verified",
            required_params=["usernames"],
            optional_params=["maxPosts"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/threads-profile-api-scraper)",
            content_type="account",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_threads_posts_scraper",
            label="Threads Posts Scraper",
            platform="threads",
            description="Threads 帖子搜索：关键词、账号、话题",
            status="verified",
            required_params=["mode"],
            optional_params=["usernames", "keywords", "max_posts"],
            cost_hint="$0.005+",
            provider="Apify Actor (futurizerush/meta-threads-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_pinterest_scraper",
            label="Pinterest Scraper",
            platform="pinterest",
            description="Pinterest Pin：视觉趋势、内容灵感",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxPinsCnt"],
            cost_hint="免费",
            provider="Apify Actor (danielmilevski9/pinterest-crawler)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_glassdoor_scraper",
            label="Glassdoor Scraper",
            platform="glassdoor",
            description="Glassdoor 评价：雇主品牌、员工反馈",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxReviews"],
            cost_hint="按事件计费",
            provider="Apify Actor (memo23/glassdoor-scraper-ppr)",
            content_type="review",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_product_hunt_scraper",
            label="Product Hunt Scraper",
            platform="product_hunt",
            description="Product Hunt 每日发布：产品趋势、创新监测",
            status="verified",
            required_params=[],
            optional_params=["maxDays"],
            cost_hint="按事件计费",
            provider="Apify Actor (happitap/product-hunt-daily-launch-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_crunchbase_scraper",
            label="Crunchbase Scraper",
            platform="crunchbase",
            description="Crunchbase 公司数据：融资、团队、投资人",
            status="verified",
            required_params=["companyUrls"],
            optional_params=["maxCompanies"],
            cost_hint="按事件计费",
            provider="Apify Actor (davidsharadbhatt/crunchbase-company-scraper)",
            content_type="account",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_hacker_news_scraper",
            label="Hacker News Scraper",
            platform="hacker_news",
            description="Hacker News 帖子与评论：科技圈舆情、产品讨论",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (onescales/hacker-news-data)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_bluesky_scraper",
            label="Bluesky Scraper",
            platform="bluesky",
            description="Bluesky 帖子：去中心化社交监测",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (fatihtahta/All-In-One-Bluesky-Scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_telegram_scraper",
            label="Telegram Channel Scraper",
            platform="telegram",
            description="Telegram 频道消息：私域流量、KOL 传播监测",
            status="verified",
            required_params=["channelUrls"],
            optional_params=["maxMessages"],
            cost_hint="按事件计费",
            provider="Apify Actor (danielmilevski9/telegram-channel-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_indeed_jobs_scraper",
            label="Indeed Jobs Scraper",
            platform="indeed",
            description="Indeed 职位信息：竞品招聘动态、人才市场",
            status="verified",
            required_params=["queries"],
            optional_params=["maxItems", "country"],
            cost_hint="按事件计费",
            provider="Apify Actor (misceres/indeed-scraper)",
            content_type="job",
            method="apify",
        ),
    ]

    # === PR Media Monitoring (Forbes, BabyCenter, Wirecutter, Good Housekeeping) ===
    # Core S/A-level media from PR planning table - social platform account monitoring
    apify_media = [
        CollectorEndpointMetadata(
            endpoint_type="apify_google_news_media_search",
            label="Google News 媒体搜索",
            platform="google_news",
            description="监测主流媒体报道：Forbes、BabyCenter、Wirecutter、Good Housekeeping 等",
            status="verified",
            required_params=["searchTerms"],
            optional_params=["maxItems", "includedDomains"],
            cost_hint="按事件计费",
            provider="Apify Actor (data_xplorer/google-news-scraper-fast)",
            content_type="news",
            method="apify",
        ),
        # Instagram monitoring for S/A-level media accounts
        CollectorEndpointMetadata(
            endpoint_type="apify_instagram_media_profile_scraper",
            label="Instagram 媒体账号监测",
            platform="instagram",
            description="监测 S/A 级媒体 Instagram：@forbesvetted @consumerreports @parents",
            status="verified",
            required_params=["usernames"],
            optional_params=["resultsLimit"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/instagram-profile-scraper)",
            content_type="account",
            method="apify",
        ),
        # TikTok monitoring for S/A-level media accounts
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_media_profile_scraper",
            label="TikTok 媒体账号监测",
            platform="tiktok",
            description="监测 S/A 级媒体 TikTok：@forbesvetted @consumerreports @parents @babylist",
            status="verified",
            required_params=["profiles"],
            optional_params=["resultsPerPage"],
            cost_hint="$0.5+",
            provider="Apify Actor (clockworks/tiktok-scraper)",
            content_type="account",
            method="apify",
        ),
        # YouTube monitoring for S/A-level media channels
        CollectorEndpointMetadata(
            endpoint_type="apify_youtube_media_channel_scraper",
            label="YouTube 媒体频道监测",
            platform="youtube",
            description="监测 S/A 级媒体 YouTube：Consumer Reports、Parents、Babylist、BabyCenter",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxResults"],
            cost_hint="按事件计费",
            provider="Apify Actor (streamers/youtube-scraper)",
            content_type="account",
            method="apify",
        ),
        # Facebook monitoring for S/A-level media pages
        CollectorEndpointMetadata(
            endpoint_type="apify_facebook_media_page_scraper",
            label="Facebook 媒体页面监测",
            platform="facebook",
            description="监测 S/A 级媒体 Facebook 页面：Forbes Vetted、Consumer Reports、Parents",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxPosts"],
            cost_hint="$0.0017+",
            provider="Apify Actor (apify/facebook-posts-scraper)",
            content_type="account",
            method="apify",
        ),
        # X/Twitter monitoring for S/A-level media accounts
        CollectorEndpointMetadata(
            endpoint_type="apify_x_media_account_scraper",
            label="X/Twitter 媒体账号监测",
            platform="x",
            description="监测 S/A 级媒体 X 账号：@ForbesVetted @ConsumerReports @parentsmagazine",
            status="verified",
            required_params=["twitterHandles"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (apidojo/tweet-scraper)",
            content_type="account",
            method="apify",
        ),
        # Pinterest monitoring for S/A-level media accounts
        CollectorEndpointMetadata(
            endpoint_type="apify_pinterest_media_profile_scraper",
            label="Pinterest 媒体账号监测",
            platform="pinterest",
            description="监测 S/A 级媒体 Pinterest：Parents、Babylist、Made for Mums、BabyCenter",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxPinsCnt"],
            cost_hint="免费",
            provider="Apify Actor (danielmilevski9/pinterest-crawler)",
            content_type="account",
            method="apify",
        ),
    ]

    # === Open Web Crawling (Website Content, Generic Scraper, RAG Browser) ===
    apify_open_web = [
        CollectorEndpointMetadata(
            endpoint_type="apify_website_content_crawler",
            label="Website Content Crawler",
            platform="web",
            description="网站内容爬虫：文章、博客、文档",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxCrawlDepth", "maxCrawlPages"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/website-content-crawler)",
            content_type="web_page",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_web_scraper",
            label="Web Scraper",
            platform="web",
            description="通用网页抓取：自定义 CSS / XPath 选择器",
            status="verified",
            required_params=["startUrls"],
            optional_params=["pageFunction", "maxCrawlDepth"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/web-scraper)",
            content_type="web_page",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_rag_web_browser",
            label="RAG Web Browser",
            platform="web",
            description="RAG 优化浏览器：Markdown 输出、AI 友好",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxCrawlDepth"],
            cost_hint="按事件计费",
            provider="Apify Actor (apify/rag-web-browser)",
            content_type="web_page",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_transcript_extractor",
            label="TikTok 视频字幕提取",
            platform="tiktok",
            description="提取 TikTok 视频的语音字幕和文字稿，用于内容 NLP 和 SEO 关键词分析",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按月计费",
            provider="Apify Actor (clockworks/tiktok-transcript-extractor)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_youtube_transcript_scraper",
            label="YouTube 视频字幕",
            platform="youtube",
            description="提取 YouTube 视频字幕/CC 文字稿，无需下载视频，用于竞品内容分析和 NLP",
            status="verified",
            required_params=["startUrls"],
            optional_params=["language"],
            cost_hint="按事件计费",
            provider="Apify Actor (johnvc/youtubetranscripts)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_creative_center",
            label="TikTok Creative Center 趋势",
            platform="tiktok",
            description="采集 TikTok Creative Center 的广告素材趋势、热门音乐和流行话题",
            status="verified",
            required_params=[],
            optional_params=["country_code", "period", "maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (doliz/tiktok-creative-center-scraper)",
            content_type="ad",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_facebook_group_scraper",
            label="Facebook Group Scraper",
            platform="facebook",
            description="采集 Facebook 公开群组帖子和讨论，获取私域社群真实 VOC",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (whoareyouanas/facebook-group-scraper)",
            content_type="post",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_similarweb_scraper",
            label="SimilarWeb 流量分析",
            platform="web",
            description="采集竞品网站流量来源、渠道占比和关键词，用于竞争情报分析",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (curious_coder/similarweb-scraper)",
            content_type="web_page",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_tiktok_shop_search_scraper",
            label="TikTok Shop 竞品商品搜索",
            platform="tiktok",
            description="搜索 TikTok Shop 商品：竞品商品详情、销量排行和达人带货数据",
            status="verified",
            required_params=["keyword"],
            optional_params=["maxItems", "sortType"],
            cost_hint="按事件计费",
            provider="Apify Actor (pratikdani/tiktok-shop-search-scraper)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_target_products_scraper",
            label="Target Products Scraper",
            platform="target",
            description="采集 Target 商品详情、价格和评价：北美第三大零售商渠道数据",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems"],
            cost_hint="按事件计费",
            provider="Apify Actor (bovi/target-products)",
            content_type="product",
            method="apify",
        ),
        CollectorEndpointMetadata(
            endpoint_type="apify_facebook_marketplace_scraper",
            label="Facebook Marketplace Scraper",
            platform="facebook",
            description="采集 Facebook Marketplace 二手商品列表和价格：二级市场价格情报",
            status="verified",
            required_params=["startUrls"],
            optional_params=["maxItems", "location"],
            cost_hint="按月计费",
            provider="Apify Actor (apify/facebook-marketplace-scraper)",
            content_type="product",
            method="apify",
        ),
    ]

    apify_endpoints = (
        apify_social
        + apify_ecommerce
        + apify_google
        + apify_ai_search
        + apify_ads
        + apify_b2b
        + apify_media
        + apify_open_web
    )

    github_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="github_repo",
            label="GitHub 仓库监测",
            platform="github",
            description="监测 GitHub 仓库的 Stars、Fork、Issue、发布和 README",
            status="verified",
            required_params=["owner", "repo"],
            optional_params=[],
            cost_hint="免费",
            provider="GitHub REST API",
            content_type="repo",
            method="github_api",
        ),
        CollectorEndpointMetadata(
            endpoint_type="github_topic",
            label="GitHub 话题发现",
            platform="github",
            description="按话题发现 GitHub 仓库，跟踪生态趋势",
            status="verified",
            required_params=["topic"],
            optional_params=["max_items"],
            cost_hint="免费",
            provider="GitHub REST API",
            content_type="repo",
            method="github_api",
        ),
    ]

    rss_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="RSS/Atom 订阅源",
            platform="rss",
            description="采集公开 RSS/Atom 订阅源的最新内容，支持 content-hash drift 检测",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="公开网页快照",
            platform="web",
            description="采集公开网页内容，生成 content-hash 用于变更检测",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
        # S级媒体 RSS 监测 (已验证可用)
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Forbes Innovation RSS",
            platform="rss",
            description="Forbes Innovation 频道 RSS: https://www.forbes.com/innovation/feed2",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Wirecutter RSS",
            platform="rss",
            description="NYT Wirecutter RSS: https://www.nytimes.com/wirecutter/feed",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        # S级媒体 RSS 监测 (待验证)
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Good Housekeeping RSS",
            platform="rss",
            description="Good Housekeeping RSS: https://www.goodhousekeeping.com/rss/all.xml",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="BabyCenter RSS",
            platform="rss",
            description="BabyCenter RSS: https://www.babycenter.com/rss/babylink.pod",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Consumer Reports RSS",
            platform="rss",
            description="Consumer Reports RSS: https://www.consumerreports.org/content/dam/cro/news_articles/health/CRPMI_RSS_Health.xml",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Parents RSS",
            platform="rss",
            description="Parents 杂志 RSS: https://www.parents.com/feeds/all.rss.xml",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        # C/D 级母婴媒体 RSS (已验证可用)
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="MomJunction RSS",
            platform="rss",
            description="MomJunction 育儿内容 RSS: https://www.momjunction.com/feed/",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Made for Mums RSS",
            platform="rss",
            description="Made for Mums 母婴评测 RSS: https://www.madeformums.com/feed/",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Mumsnet RSS",
            platform="rss",
            description="Mumsnet 社区内容 RSS: https://www.mumsnet.com/rss",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Healthline Parenting RSS",
            platform="rss",
            description="Healthline 健康育儿新闻 RSS: https://www.healthline.com/rss/health-news",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="BabyGaga RSS",
            platform="rss",
            description="BabyGaga 母婴内容 RSS: https://www.babygaga.com/feed/",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Romper RSS",
            platform="rss",
            description="Romper 母婴生活内容 RSS: https://www.romper.com/rss",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        # C/D 级母婴媒体 RSS (不可用)
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="The Bump RSS",
            platform="rss",
            description="The Bump 孕期育儿 RSS: https://www.thebump.com/rss",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="What to Expect RSS",
            platform="rss",
            description="What to Expect 孕期育儿 RSS: https://www.whattoexpect.com/rss",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Verywell Family RSS",
            platform="rss",
            description="Verywell Family 育儿资讯 RSS: https://www.verywellfamily.com/rss",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Scary Mommy RSS",
            platform="rss",
            description="Scary Mommy 母婴内容 RSS: https://www.scarymommy.com/feed",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="Working Mother RSS",
            platform="rss",
            description="Working Mother 职场妈妈 RSS: https://www.workingmother.com/rss",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="feed",
            method="rss",
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="The Stir (CafeMom) RSS",
            platform="rss",
            description="The Stir CafeMom 母婴社区 RSS: https://thestir.cafemom.com/feed/",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
        ),
        # PR 媒体 Listicle 网页快照监测 (generic_web)
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="Forbes Vetted 母婴 Listicle",
            platform="web",
            description="Forbes Vetted 母婴/育儿 Listicle: https://www.forbes.com/sites/forbes-personal-shopper/",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="Wirecutter 母婴最佳推荐",
            platform="web",
            description="Wirecutter 母婴/育儿产品推荐: https://www.nytimes.com/wirecutter/baby-kids/",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="Good Housekeeping 母婴推荐",
            platform="web",
            description="Good Housekeeping 母婴产品推荐: https://www.goodhousekeeping.com/childrens-products/",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="Babylist 推荐产品页",
            platform="web",
            description="Babylist 产品推荐/注册礼单: https://www.babylist.com/hello-baby/",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="BabyCenter 产品推荐",
            platform="web",
            description="BabyCenter 产品推荐: https://www.babycenter.com/baby-products",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="generic_web",
            label="Consumer Reports 母婴评测",
            platform="web",
            description="Consumer Reports 母婴/育儿产品评测: https://www.consumerreports.org/baby-kids/",
            status="disabled",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="web_page",
            method="web_crawl",
        ),
    ]

    browser_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="playwright_browser_text",
            label="浏览器采集 - 正文文本",
            platform="web",
            description="Headless Chromium renders the page and extracts visible body text.",
            status="verified",
            required_params=["url"],
            optional_params=["wait_for", "wait_selector"],
            cost_hint="免费",
            provider="自研 Playwright Collector",
            content_type="web_page",
            method="browser",
        ),
        CollectorEndpointMetadata(
            endpoint_type="playwright_browser_html",
            label="浏览器采集 - 完整 HTML",
            platform="web",
            description="Headless Chromium renders the page and returns the full HTML source.",
            status="verified",
            required_params=["url"],
            optional_params=["wait_for", "wait_selector"],
            cost_hint="免费",
            provider="自研 Playwright Collector",
            content_type="web_page",
            method="browser",
        ),
        CollectorEndpointMetadata(
            endpoint_type="playwright_browser_screenshot",
            label="浏览器采集 - 截图",
            platform="web",
            description="Headless Chromium renders the page and captures a full-page screenshot.",
            status="verified",
            required_params=["url"],
            optional_params=["wait_for", "wait_selector"],
            cost_hint="免费",
            provider="自研 Playwright Collector",
            content_type="web_page",
            method="browser",
        ),
    ]

    jina_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="jina_page_content",
            label="Jina Reader 通用页面转 Markdown",
            platform="web",
            description="Convert any public web page to clean Markdown via r.jina.ai.",
            status="verified",
            required_params=["url"],
            optional_params=["return_format"],
            cost_hint="~0.001 credits/page",
            provider="Jina AI",
            content_type="web_page_markdown",
            method="jina_reader",
        ),
        CollectorEndpointMetadata(
            endpoint_type="jina_dtc_review",
            label="Jina Reader DTC 评价页采集",
            platform="web",
            description="Extract review page content from DTC brand sites via r.jina.ai.",
            status="verified",
            required_params=["url"],
            optional_params=["return_format"],
            cost_hint="~0.001 credits/page",
            provider="Jina AI",
            content_type="web_page_markdown",
            method="jina_reader",
        ),
        CollectorEndpointMetadata(
            endpoint_type="jina_news_article",
            label="Jina Reader 新闻文章正文提取",
            platform="web",
            description="Extract clean article text from news pages via r.jina.ai.",
            status="verified",
            required_params=["url"],
            optional_params=["return_format"],
            cost_hint="~0.001 credits/page",
            provider="Jina AI",
            content_type="web_page_markdown",
            method="jina_reader",
        ),
    ]

    anysearch_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="anysearch_brand_media",
            label="AnySearch 品牌×媒体覆盖查询",
            platform="web",
            description="Search brand mentions across media sites via AnySearch API.",
            status="verified",
            required_params=["query"],
            optional_params=["site", "num_results"],
            cost_hint="$0.001/query",
            provider="AnySearch API",
            content_type="search_result",
            method="anysearch",
        ),
        CollectorEndpointMetadata(
            endpoint_type="anysearch_competitor",
            label="AnySearch 竞品动态搜索",
            platform="web",
            description="Search competitor brand news and reviews via AnySearch API.",
            status="verified",
            required_params=["query"],
            optional_params=["site", "num_results"],
            cost_hint="$0.001/query",
            provider="AnySearch API",
            content_type="search_result",
            method="anysearch",
        ),
    ]

    regulatory_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="FDA Food Safety Recalls RSS",
            platform="regulatory",
            description="US FDA food safety recalls and market withdrawals RSS feed.",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 RSS Collector",
            content_type="news",
            method="rss",
            param_fields={
                "url": "https://www.fda.gov/about-fda/contact-fda/stay-informed/rss-feeds/food-safety-recalls/rss.xml"
            },
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="UK OPSS Product Safety Recalls",
            platform="regulatory",
            description="UK Office for Product Safety and Standards product recall notices (Atom).",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 RSS Collector",
            content_type="news",
            method="rss",
            param_fields={
                "url": "https://www.gov.uk/search/all.atom?keywords=product+safety+recall&order=updated-newest"
            },
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="UK NHS Medicines & Devices Alerts",
            platform="regulatory",
            description="UK NHS medical device and drug safety alerts (Atom feed, 50 latest).",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 RSS Collector",
            content_type="news",
            method="rss",
            param_fields={
                "url": "https://www.gov.uk/drug-device-alerts.atom"
            },
        ),
        CollectorEndpointMetadata(
            endpoint_type="public_feed",
            label="PR Newswire Product Recalls",
            platform="regulatory",
            description="PR Newswire product recall press releases RSS (global brands).",
            status="verified",
            required_params=["url"],
            optional_params=[],
            cost_hint="免费",
            provider="自研 RSS Collector",
            content_type="news",
            method="rss",
            param_fields={
                "url": "https://www.prnewswire.com/rss/news-releases-list.rss?category=PRODUCT_RECALLS"
            },
        ),
    ]

    ecommerce_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="ecommerce_product_page",
            label="独立站商品页采集",
            platform="ecommerce",
            description="解析公开独立站商品页，提取标题、价格、库存、SKU、品牌、描述、图片等结构化字段。",
            status="verified",
            required_params=["url"],
            optional_params=["fields", "platform_hint"],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="product",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="ecommerce_product_discovery",
            label="独立站商品 URL 发现",
            platform="ecommerce",
            description="Discover product URLs from an ecommerce site (Shopify / generic).",
            status="verified",
            required_params=["url"],
            optional_params=["max_products", "platform_hint"],
            cost_hint="免费",
            provider="自研 HTTP Collector",
            content_type="product",
            method="web_crawl",
        ),
    ]

    osint_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="sherlock_username_search",
            label="Sherlock 用户名追踪",
            platform="web",
            description=(
                "跨 400+ 社交平台检查指定用户名是否存在，"
                "返回每个平台的主页 URL。常用于 KOL 身份核实和品牌仿冒检测。"
            ),
            status="verified",
            required_params=["username"],
            optional_params=["sites"],
            cost_hint="免费",
            provider="sherlock-project (开源)",
            content_type="account",
            method="web_crawl",
        ),
        CollectorEndpointMetadata(
            endpoint_type="maigret_username_profile",
            label="Maigret 用户名画像",
            platform="web",
            description=(
                "跨 3000+ 平台构建用户名档案，返回每个平台的账号状态和主页 URL。"
                "比 Sherlock 覆盖更广但速度较慢。"
            ),
            status="verified",
            required_params=["username"],
            optional_params=["max_sites"],
            cost_hint="免费",
            provider="maigret (开源)",
            content_type="account",
            method="web_crawl",
        ),
    ]

    twscrape_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="twscrape_search",
            label="X/Twitter 关键词搜索",
            platform="x",
            description=(
                "通过 twscrape 免费搜索 X/Twitter 推文，"
                "支持 Latest / Top / Media 三种搜索模式，多账号轮换自动限流处理。"
            ),
            status="verified",
            required_params=["query"],
            optional_params=["limit", "product"],
            cost_hint="免费（需账号 Cookie）",
            provider="twscrape (开源)",
            content_type="post",
            method="twscrape",
        ),
        CollectorEndpointMetadata(
            endpoint_type="twscrape_user_tweets",
            label="X/Twitter 用户时间线",
            platform="x",
            description=(
                "获取指定 X/Twitter 用户的公开推文列表，最多 3200 条，"
                "返回推文内容、互动数据和作者信息。"
            ),
            status="verified",
            required_params=["username"],
            optional_params=["limit"],
            cost_hint="免费（需账号 Cookie）",
            provider="twscrape (开源)",
            content_type="post",
            method="twscrape",
        ),
        CollectorEndpointMetadata(
            endpoint_type="twscrape_trends",
            label="X/Twitter 热门趋势",
            platform="x",
            description=(
                "获取 X/Twitter 指定分类（news / sport / entertainment）的热门话题趋势列表。"
            ),
            status="verified",
            required_params=[],
            optional_params=["category"],
            cost_hint="免费（需账号 Cookie）",
            provider="twscrape (开源)",
            content_type="trend",
            method="twscrape",
        ),
    ]

    anydoc_endpoints = [
        CollectorEndpointMetadata(
            endpoint_type="anydoc_file_to_markdown",
            label="文档转 Markdown",
            platform="web",
            description=(
                "将远程 Word (.docx)、PowerPoint (.pptx)、Excel (.xlsx)、"
                "PDF、EPUB、RTF、CSV 等文档文件转换为干净的 Markdown 格式。"
                "适用于供应商文件、政府公文、竞品白皮书的结构化处理。"
            ),
            status="verified",
            required_params=["file_url"],
            optional_params=["file_type"],
            cost_hint="免费",
            provider="anydoc (开源 Rust)",
            content_type="web_page_markdown",
            method="web_crawl",
        ),
    ]

    return CollectorCatalogResponse(
        collectors=[
            CollectorCatalogEntry(
                collector_type="tikhub_social",
                label="TikHub Social",
                platform="tikhub",
                endpoints=tikhub_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="apify_actor",
                label="Apify Actors",
                platform="apify",
                endpoints=apify_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="github",
                label="GitHub",
                platform="github",
                endpoints=github_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="rss_web",
                label="RSS / 公开网页",
                platform="web",
                endpoints=rss_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="browser",
                label="浏览器自动化",
                platform="web",
                endpoints=browser_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="ecommerce_web",
                label="电商独立站",
                platform="ecommerce",
                endpoints=ecommerce_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="regulatory",
                label="监管 / 召回公告",
                platform="regulatory",
                endpoints=regulatory_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="anysearch",
                label="AnySearch 搜索采集",
                platform="web",
                endpoints=anysearch_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="jina_reader",
                label="Jina Reader 页面转 Markdown",
                platform="web",
                endpoints=jina_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="osint",
                label="OSINT 用户名追踪",
                platform="web",
                endpoints=osint_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="twscrape",
                label="X/Twitter 免费多账号采集",
                platform="x",
                endpoints=twscrape_endpoints,
            ),
            CollectorCatalogEntry(
                collector_type="anydoc",
                label="文档转 Markdown",
                platform="web",
                endpoints=anydoc_endpoints,
            ),
        ]
    )
